### ISSUE TITLE
Camera box not appearing

### ISSUE THREAD

**Issue by oleteacher** [jeeliz/jeelizWeboji#1]
Totally cool app!

I am running Chrome Version 67.0.3396.99 (Official Build) (64-bit) and have allowed access to cam.

Nothing happens on the screen with either of your example demos. The cute fox, nothing but a background image with rounded lines on screen. The SVG appears on the other one but nothing else. No camera box in lower corner as shown in your example screenshot.

Is this for MAC/Apple only, or will it run on Windows?

Thanks.

**Comment by irkawajan** [comment]
+1

**Comment by irkawajan** [comment]
https://github.com/jeeliz/jeelizWeboji#hosting

**Comment by irkawajan** [comment]
+1

**Comment by bjlaa** [comment]
Hi,

Thank you for your interest in jeelizWebojis. I just tested the example demos on Windows with Chrome version 67.0.3396.99 (Official Build)(64 bits). Everything was working as expected (both the cute fox and the SVG demos, with the video feed on the lower corner).
Could you check in your console if any errors show up when you run the demos? Also, you should make sure that your video device isn't used in another tab, or app (i.e Skype) before visiting the demos.

**Comment by xavierjs** [comment]
Hi Oleteacher,

Can you try a simple WebRTC demo like this one : https://webrtc.github.io/samples/src/content/getusermedia/gum/
Just to be sure the problem does not come from the webcam access ?

Thank you,
Xavier

**Comment by oleteacher** [comment]
Hi @xavierjs and @bjlaa 

I finally got around to trying on another computer and it works as expected. Must be something to do with the webcam as both computers are same brand, same version of Chrome and both Win10 Pro.

On computer that does not work, there are no errors shown in dev console.

If I do find the issue will certainly share my finding.

Thank you both for your input and help.
