### ISSUE TITLE
How to change the color of the blue bounding box?

### ISSUE THREAD

**Issue by Andyjoedev** [jeeliz/jeelizWeboji#11]
Hello Jeeliz Team,

Thank you for Weboji! Great work!

I want to change the color of the blue bounding box on the canvas. How to do so?

Regards, 
Andy

**Comment by xavierjs** [comment]
Hi @Andyjoedev 

This is not a big deal to add it, I will commit the change soon.
Best,
Xavier

**Comment by xavierjs** [comment]
Hi,

The modification has been added and commited.
You can change the color of the frame by calling (after the init step):
```
JEEFACETRANSFERAPI.set_color([1,0,0]); //--> for red color
```
See the .PDF doc for more information.

Best,
Xavier

**Comment by Andyjoedev** [comment]
Thank you for quick modification. 
I am impressed with your dedication on this project. 
I will check the function soon.

Regards,
Andy
