### ISSUE TITLE
How to set the dimension and position of bounding box?

### ISSUE THREAD

**Issue by Andyjoedev** [jeeliz/jeelizWeboji#12]
Hello Jeeliz Team,
Thanks again for creating this wonderful library!

I am building a project where the user is generally sitting in between with very little side rotation. I want to set the bounding box to a limited area and not to the full canvas. This will increase the searching speed for face if the tracking fails.
How can I accomplish this?

Regards,
Andy

**Comment by xavierjs** [comment]
Hi Andy
This is currently not possible. 
You should suggest to your users to get closer to their webcam. 
Indeed if the user is too far from the webcam the cropped portion of the image matching the face and given as input for the neural network has à lower quality.

If you still want to add this feature we provide tailored development services, Please contact us on contact__at__jeeliz.com


Best 
Xavier

**Comment by Andyjoedev** [comment]
Thanks for your quick reply,

My project is not for any commercial use. I am a student and want to learn things by experimenting with them. 

The only issue I got from your algorithm was that face detection after tracking failure is very slow. The only way to fix this without improving the face tracking accuracy is by limiting the bounding box to a smaller size. Also, in my solution user sits in the middle of the camera.  So this theory was certainly applicable. 

> "You should suggest to your users to get closer to their webcam."
This is one way to do so but the result will be a larger face which I don't want.

Can we set the size of the user face canvas "jeefacetransferCanvas" ? Is so how?

If this also goes into tailored development category feel free to skip this question. 

Thank you very much

Regards
Andy

**Comment by xavierjs** [comment]
Hi,

It also depends a lot on the GPU computing power of the device and the quality of the WebGL implementation. Then there are a lot of face placements depending on the device: user will be closer on mobile phone than laptops, and it also depends on the camera FoV. So to be sure the detection window has to slide accross many possible positions and yes, it can be a bit slow.

This issue explains how to get the coordinates of the face detection:
https://github.com/jeeliz/jeelizWeboji/issues/8

Best,
Xavier
