### ISSUE TITLE
Can I make a bounding box a circle?

### ISSUE THREAD

**Issue by takuya-motoshima** [jeeliz/jeelizWeboji#17]
Hello Jeeliz Team,

Thank you for the great job.

I want to make the shape of the bounding box of the canvas a circle. How to do so?

Regards

**Comment by xavierjs** [comment]
Hi,

I can add this feature for a customized version of the library.
You can contact me directly at xavier__at__jeeliz.com and I will send you a proposal for this development service :) .

Best regards,
Xavier

**Comment by takuya-motoshima** [comment]
Thanks for your quick reply.

I want a customized library.

I sent you an email.Verification please.

Below is my email address
developer.takuyamotoshima@gmail.com





xavier@jeeliz.com
