### ISSUE TITLE
Get the capacities of devices

### ISSUE THREAD

**Issue by sonidiaz** [jeeliz/jeelizWeboji#19]
Hi @xavierjs,
A question, do you have a some helpers  with i can get if the device have or not the capacities for jobs with the libraries?
Is for not load the Jeeliz if the device not have the capacities and search other alternative.
Thanks!

**Comment by xavierjs** [comment]
Hi,

I don't have these libraries, basically you have to check whether the user have WebGL2 or WebGL1 + texture float or half float.

Best,
Xavier

**Comment by sonidiaz** [comment]
Perfect!!
Thanks @xavierjs!
