### ISSUE TITLE
Capture frame

### ISSUE THREAD

**Issue by canvasandcode** [jeeliz/jeelizWeboji#23]
Is there a way to capture the frame. For example if a button was on the page, on click will capture a frame as JPEG and display that on a page so that it can be shared?

**Comment by xavierjs** [comment]
Related to https://github.com/jeeliz/jeelizWeboji/issues/20 for video capture.

To get a JPEG or PNG image from the canvas you need to use `canvas.toDataURL()` ( https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL )

Then if you want to handle the sharing you have to send it server side and serve it.
