### ISSUE TITLE
running a function if face detected

### ISSUE THREAD

**Issue by canvasandcode** [jeeliz/jeelizWeboji#24]
Hi, how can I run a function if a face is detected/ not detected? I can't seem to find any existing functions in the source file controlling the detection. Is there anything I should be targeting?

**Comment by xavierjs** [comment]
Like in almost all the demos provided, you have to check `detectState.detected' value and compare it to a threshold (typically if <0.5 it is not a face, otherwise it is a face).

**Comment by canvasandcode** [comment]
I get a 'detectState is not defined', I've even searched all files from the demo/source file for 'detect' / 'detectState' but it finds nothing

**Comment by xavierjs** [comment]
Look at the doc: https://github.com/jeeliz/jeelizWeboji/blob/master/doc/jeefacetransferAPI.pdf
function `on_detect`

**Comment by xavierjs** [comment]
I close the issue since I think a proper answer was given. Feel free to re-open it if it does not work.
