### ISSUE TITLE
Error in device with WebGL2

### ISSUE THREAD

**Issue by sonidiaz** [jeeliz/jeelizWeboji#26]
Hi @xavierjs, me again :)
I am doing tests and I have encountered a special case. With the Samsung A5 from 2016 ... that has WebGl2 throw the following error:
**ERROR in ContextFeedForward: Not enough capabilities**
Why is it wrong? Is there any way to capture that error with a browser or device test?
Thanks!!

**Comment by xavierjs** [comment]
Hi,

I just tested on a Samsung A5  bought in early 2017 this demo with Chrome: https://jeeliz.com/demos/weboji/demos/threejs/raccoon/
And it works.
Are you sure you are using the latest Weboji version?

But the demo was too slow. Indeed the neural network model is quite heavier (heavier than the one used in Jeeliz FaceFilter for example). The weboji feature is more built for higher end mobile phones. It should work nicely with a Samsung S7, a Huawei P9, it works correctly on mine (a 4yo Sony Xperia Zperformance).

**Comment by sonidiaz** [comment]
Hi, thanks for the quick response as always.
I am trying with your demo and I have the same error and I add this: **ERROR: JEEFACETRANSFERAPI cannot be started. errCode = GL_INCOMPATIBLE.** 
This device has WebGl2.
Thanks!

**Comment by sonidiaz** [comment]
Yes it's strange. I'll continue testing.
Thanks !!

**Comment by xavierjs** [comment]
Hi what's up about this error? Did you tried after updating Android, closing all apps and reboot your phone?

**Comment by sonidiaz** [comment]
Hi, I don't have tried again with that device, As soon as I have it I will. Thanks for asking

**Comment by xavierjs** [comment]
Hi @sonidiaz 

I have just pushed a new neural network model which is faster and lighter than the previous one (the accuracy is still the same).
On my medium end mobile phone it really makes a difference (4yo Sony Xperia Zperformance, same computing power than Iphone6).

Best,
Xavier

**Comment by sonidiaz** [comment]
Hi @xavierjs, 

it's great!! 
As soon as i can i will do test with last release.

Best,
Nacho

**Comment by xavierjs** [comment]
Hi,
I close the issue since I have no news about this bug.
If it still happens, fee free to re-open it :)
