### ISSUE TITLE
Hardware requirements

### ISSUE THREAD

**Issue by mark9067** [jeeliz/jeelizWeboji#30]
Hello, thank you for the work you do for this library.
I would like to know the minimum hardware requirements.
a pc with 4gb of ram and an Intel Atom x5-Z8350 processor
with windows 10 can it work?
thanks

**Comment by xavierjs** [comment]
Hi,

It depends more on the GPU. All computations are done on the GPU, for the deep learning network. The more the GPU is powerful, the more we can run the neuron network per second, and the more the result will be accurate and without delays.

Then I don't have exact metrics about GPU performance. The best is to try some devices.
My mobile phone, a 4 yo Sony Xperia Zperformance seems to be the lower bound to have a good experience.

4GB of RAM is far enough, the lib does not use a lot of RAM (something like 20MB)
For the OS, it should work even with windows 7.

**Comment by mark9067** [comment]
Hi,
Thanks for the reply.
Have you tried on an intel stick or a mini pc?

**Comment by xavierjs** [comment]
Hi,

Intel stick, rpi, ... have very weak gpus.
If you want a small setup you should go with a Nvidia Jetson.
It works very well on the TX2, and I think the Jetson nano would be fine.

**Comment by mark9067** [comment]
Ok, thanks for the advice. I think I start  on a jetson nano.
I would like to know if I can resell this device to my clients, and if it is a device that can remain on 24h / 24h 7 / 7j without problem ?
Thank you

**Comment by xavierjs** [comment]
Hi,

You can use this software stack to run JS apps on jetson: https://github.com/jeeliz/jetsonjs
The Jetson can run without interruption.

You are welcome to give any feedback using a specific hardware :).

Best,
Xavier
