### ISSUE TITLE
Typo in Readme.md

### ISSUE THREAD

**Issue by abhilash26** [jeeliz/jeelizWeboji#36]
Hello Jeeliz,

Just wanted to inform you that there is a typo in readme.md file 
It should be indeed not indead.

> **Indead**, Apple© owns the intellectual property of 3D animated foxes (but not on raccoons yet). Thank you for your understanding.

Nothing major.

Regards,
Abhilash

**Comment by xavierjs** [comment]
Hi @abhilash26 

Thanx, I have committed the fix.

Best,
Xavier
