### ISSUE TITLE
Hide blue box in JEEFACETRANSFERAPI

### ISSUE THREAD

**Issue by sonidiaz** [jeeliz/jeelizWeboji#4]
Hi guys,

I congratulate them you on the project, it's amazing!

I have a question, Is it possible to remove the blue box that appears on the face jeelizFaceTransfer.js?
I need to take a screenshot (canvasScreen.getContext ('2d'). DrawImage () ..) but I do not want to show that frame.

The quick solution I came up with is to create another canvas context with the video and hide the instance JEEFACETRANSFERAPI.switch_displayVideo (false);
But, I do not know if it is the best solution.

Thanks!!

**Comment by xavierjs** [comment]
Hi bro,

The canvas displaying the video feedback is very low resolution.
I think you should initialize a new `<canvas>` element with a canvas2D context and copy directly the `<video>` element displaying the webcam video feed using `drawImage` (hidden in the DOM).
Or directly do a `video.toDataURL...`.

You can get the `<video>` element using JEEFACETRANSFERAPI `videoElement` parameters given at the init callback (more info here: https://github.com/jeeliz/jeelizWeboji/blob/master/doc/jeefacetransferAPI.pdf)

Best,
Xavier

**Comment by sonidiaz** [comment]
Thanks @xavierjs !!!
