### ISSUE TITLE
Have a question about how you handle changing emotion in real time.

### ISSUE THREAD

**Issue by miyabi-dev** [jeeliz/jeelizWeboji#40]
I have a question related to this demo (jeelizWeboji/demos/threejs/raccoon).

I think that  2 important roles of JEEFACETRANSFERAPI in this demo are
1. Calculate direction of the head in real-time just like
`const rotation = JEEFACETRANSFERAPI.get_rotationStabilized(); // in animate()`
2. **Also calculate morph coefficients in real-time for morph blending.**

I tried to find where those morph coefficients are calculated, but I could only find `const morphTargetInfluencesDst = JEEFACETRANSFERAPI.get_morphTargetInfluencesStabilized(); // in successCallBack() of ThreeMorphAnimGeomBuilder()`. 
And this, in contrast to calculating the rotation in animate(), seems like **not calculating the coefficients in real-time**.
If you don't calculate those morph coefficients in real-time, how do you track clients face expression that changes in real-time?

I guess most of the calculations for animation are done in GPU using GLSL, so I want to know where your API extract information(morph coefficients?) required for morph animation from the video stream.

This demo works pretty well, so I must misunderstand something about morph animation or your API.

If you could help me untangle this problem, I really appreciate it!

Thank you for reading and sharing this **awesome** project!

**Comment by miyabi-dev** [comment]
!!! UPDATE !!!

Hi, questioner again.

I tried putting this code in animate()
`console.log(JEEFACETRANSFERAPI.get_morphTargetInfluencesStabilized())`
and I am now sure that this method returns morph coefficients that change as the client smiles or closes eys.

So these morph coefficients must be used for animation.
1. But where is the method called many times in real-time? It seems to be called only once in successCallback() of ThreeMorphAnimGeomBuilder().
2. Also, where are those morph coefficients passed to the animation code?

**Comment by miyabi-dev** [comment]
!!! UPDATE !!!

Questioner again.

According to some articles as [this](https://stackoverflow.com/questions/17952916/morph-targets-three-js), what we only need to do while the animation is going on is constantly passing morph coefficients to the corresponding index of geometry.morphTargetInfluences[] array, and Three.js(and GLSL) does morph blending for us in background.

Am I right?

I still can't find where those morph coefficients are passed to the background process.

**Comment by timsun28** [comment]
Hi,

I'm not related to this project, but I'm currently using it as well. 
I think most of the magic happens in the jeelizFaceTransfer file. Unfortunately this file is minimized, so it's difficult to find function names etc. I did find some code in there that might be able to put you on a new path to find the code that updates these parameters you talked about. 

If you reformat the code in a modern code editor, you can look for this and go from there: 

`navigator.mediaDevices.getUserMedia(h).then(function (m) {
        function n() {
            setTimeout(function () {
                if (b.currentTime) {
                    var q = b.videoWidth, g = b.videoHeight;
                    if (0 === q || 0 === g) k("VIDEO_NULLSIZE"); else {
                        q && (b.style.width = q.toString() + "px");
                        g && (b.style.height = g.toString() + "px");
                        q = {jc: null, od: null, Qc: null};
                        try {
                            var r = m.getVideoTracks()[0];
                            r && (q.Qc = r, q.jc = r.getCapabilities(), q.od = r.getSettings())
                        } catch (u) {
                        }
                        $a() || Ya() ? b.parentNode && null !== b.parentNode ? (l || d(b, m,
                            q), setTimeout(function () {
                            b.play()
                        }, 100)) : (document.body.appendChild(b), fb(b), l || d(b, m, q), setTimeout(function () {
                            b.style.transform = "scale(0.0001,0.0001)";
                            b.style.position = "fixed";
                            b.style.bottom = "0px";
                            b.style.right = "0px";
                            fb(b);
                            setTimeout(function () {
                                b.play()
                            }, 100)
                        }, 80)) : l || d(b, m, q)
                    }
                } else k("VIDEO_NOTSTARTED")
            }, 700)
        }`

If you are planning on using this project as well to build an app, maybe we can stay in contact and to help each other while developing? Let me know if you would be interested in that. 

Thanks, Timo

**Comment by xavierjs** [comment]
JEEFACETRANSFERAPI provides an array with 11 morph coefficients.
Then we apply these factors in the vertex shader.
JEEFACETRANSFER directly changes the array, which is not copied but passed by reference.
We don't use the default THREE.js morph anim mesh stuffs since it is limited to 6 morphs applied simultaneously (or something like that). This limitation is linked to the maximum number of attributes we can have in the vertex shader (usually 16). So we have to multiplex morph values in the attributes.
