### ISSUE TITLE
Only head tracking (orientation)?

### ISSUE THREAD

**Issue by marclava** [jeeliz/jeelizWeboji#43]
So far, only the jeelizWeboji demos worked for me (other demos were not able to detect my head). All I need is head tracking, with only its orientation (no face expression, emotion, etc). Can a simplest (and maybe more robust) model could be developed, that would require even less CPU resources?

**Comment by xavierjs** [comment]
Hi @marclava 

You should use https://github.com/jeeliz/jeelizFaceFilter for that.
it uses less GPU resources.
If a demo is not working please submit an issue on FaceFilter repo there detailling these informations: https://github.com/jeeliz/jeelizFaceFilter#compatibility
