### ISSUE TITLE
How to destroy?

### ISSUE THREAD

**Issue by lacastorine** [jeeliz/jeelizWeboji#46]
jeelizFaceFilter have 'native' destroy method, how to do it correctly for jeelizWeboji?

**Comment by xavierjs** [comment]
There is no `destroy()` method for weboji

**Comment by xavierjs** [comment]
`JEEFACETRANSFERAPI.destroy()` should make the job now

**Comment by lacastorine** [comment]
It is not working as expected for me:
- it is not stoping webcam stream
- it is not removing 'display:none;' style from canvas (when using JEEFACETRANSFERAPI.switch_displayVideo(false);)
- it is not possible to reinit api - it returns ALREADY_INITIALIZED error code, when I try to init api again
