### ISSUE TITLE
A question about turtle example

### ISSUE THREAD

**Issue by eduardorangell** [jeeliz/jeelizWeboji#47]
Hello, first of all thank you very much for sharing this amazing project, its incredible to see what you did with javascript 😊 
I was looking for the other examples and i saw a turtle with body, and of course i tried to see how a turtle with body looks like but i couldn't make it work it. I'm sorry for my dumb question but, Do you have an instruction to convert the `corps_tortue.obj` and reference into javascript ?
Thank you very much for your attention.

**Comment by xavierjs** [comment]
Instructions are here: https://github.com/jeeliz/jeelizWeboji/tree/master/meshConverter
