### ISSUE TITLE
detecting live person rather than Mobile video / static image

### ISSUE THREAD

**Issue by akhirai560** [jeeliz/jeelizWeboji#48]
Is there any possiblity that face-detection should neglect detection from mobile videos / static printed pictures.

I am trying to use this awesome lib for liveness detection and these are hurdles i am facing.

**_One idea is to look for rectangular shapes around images through edge- detection algo._**

Thanks, in advance

**Comment by xavierjs** [comment]
There is demo where is detection is done from a video file: https://jeeliz.com/demos/weboji/demos/threejs/externalVideo/
The source code is provided in this repo.

**Comment by akhirai560** [comment]
No i mean library can detect that the person is not real. 

Or 

Someone is showing a video from there phone
