### ISSUE TITLE
How to get translation values?

### ISSUE THREAD

**Issue by annajonesdev** [jeeliz/jeelizWeboji#5]
Sir, 
I want to get the value of how much the user has moved from the center of the screen (i.e translation (XYZ) of the face). I want to move the model just as the user is moving. Even the relative change of the blue square will work. 

I feel that jeelizFaceTransfer.js file is responsible for this. It is too complex for me to understand. Its like converted from a machine. I have found no functions that may help me. 
Please tell me how to get translation values?

**Comment by xavierjs** [comment]
Hi,

I have added the method `get_positionScale`, which returns an array with px,py,scale. The PDF doc has been updated for more information.
This position is quite raw, maybe you should stabilize it a bit with a mean filter/floating average.

Best

**Comment by annajonesdev** [comment]
Sir, 
Thanks for the quick reply. You have an awesome code here.
I am working on an application using Weboji. I am very grateful to your entire team for this solution.
I will check that function and the doc and provide you the feedback soon.

Thanks and Regards
Anna

**Comment by xavierjs** [comment]
Great, I would love to see the result and I can add a link from the readme of this library to your application.

Best regards,
Xavier
