### ISSUE TITLE
Getting error while using file jeelizFaceTransfer.js

### ISSUE THREAD

**Issue by parasjain06** [jeeliz/jeelizWeboji#54]
i am using this file " jeelizFaceTransfer.js" in my project to call a function 
but i am getting below error in the console:-
Error:-
![image](https://user-images.githubusercontent.com/63651642/89704173-517d8800-d96f-11ea-80cb-85b9f5122eb8.png)

Steps to reproduce:-
1) Download the project  from :- https://github.com/abhilash26/sit-straight
2)  run index.html in chrome

it will ask for camera permission, click ok
now camera does not open and black screen with loading logo is displayed continuosly and console displays error.

Also try to run this project in Internet Explorer, camera is open and working fine

NOTE:- Issue is with browser compatibility. not working with chrome/Firefox

WEBGL1 Screenshot:-
![image](https://user-images.githubusercontent.com/63651642/89704137-1e3af900-d96f-11ea-8319-3725b42bb464.png)

WEBGL2 Screenshot:-
![image](https://user-images.githubusercontent.com/63651642/89704122-0c595600-d96f-11ea-86e4-67c5f60a1d29.png)

Below screenshot for the console output:-
![image](https://user-images.githubusercontent.com/63651642/89704103-eb910080-d96e-11ea-8b94-76b6aa4be122.png)

**Comment by xavierjs** [comment]
You need to run it using an HTTPS local server, not as a local file.
I close the issue since it is not related to the lib, but to the basics of web dev.
