### ISSUE TITLE
get_rotation()[2] means left rotation of head is not working properly as compared to right side head rotation.

### ISSUE THREAD

**Issue by akhirai560** [jeeliz/jeelizWeboji#55]
The get_rotation()[2] does not change properly and is always in between 0.0 to 0.15.
Compared to that  get_rotation()[1] right side rotation is between 0.1 to 0.6 .

**Comment by xavierjs** [comment]
`get_rotation()` provides Euler's angle; `get_rotation()[2] ` and `get_rotation()[1]` are rotation around different axis
