### ISSUE TITLE
Error when not running on localhost

### ISSUE THREAD

**Issue by matiasvillanueva** [jeeliz/jeelizWeboji#56]
When I try to run a basic script in a server I get this error.

![Screenshot_20201005_202620](https://user-images.githubusercontent.com/15146457/95142073-377edc80-0749-11eb-8fb7-851458f4c89e.png)

But it works fine on localhost. I do no get what is the difference.

Tested on Firefox 81.0 (Linux) and Chrome 83.0.4103.116 (Linux)

**Comment by xavierjs** [comment]
What do you want me to do with such an error message?
I don't know which demo you are trying if you try if with HTTPS, ...
The warning error looks very explicit, your canvas should not have well defined width and height.
