### ISSUE TITLE
Is there any method to convert face landmarks to expression?

### ISSUE THREAD

**Issue by duchengyao** [jeeliz/jeelizWeboji#58]
I got facial landmarks like [this image](https://www.researchgate.net/figure/The-68-Multi-PIE-landmarks-scheme-and-the-landmarks-selected-for-our-method-marked-by-the_fig1_311741971). How to convert landmarks to [this expression](https://github.com/jeeliz/jeelizWeboji#under-the-hood)?

Thanks!

**Comment by xavierjs** [comment]
I close this issue since I don't see any relation to this library.
