### ISSUE TITLE
How can I get the coordinates of facial landmark detection?

### ISSUE THREAD

**Issue by smithjacksondev** [jeeliz/jeelizWeboji#6]
Like [clmtrackr](https://github.com/auduno/clmtrackr), how to get facial landmarks detection coordinates?

**Comment by xavierjs** [comment]
Hi,

There is no facial landmarks detection.
We perform global detection.

**Comment by smithjacksondev** [comment]
Well then, thanks anyway.
You have given me enough already.
The detection sure is stable and the animation looks really good.
I wish I can contribute to your code.
Regards
Smith

**Comment by xavierjs** [comment]
Hi,

If you have some demos or apps using this lib, I would be thrilled to add a link from the readme of this github repository.
Also I am working on landmark detection, but the project has been delayed and it will not be free.
It will still be a very accessible price compared to the competitors.

Best,
Xavier
