### ISSUE TITLE
JEEFACETRANSFERAPI : set_animateDelay : missed method

### ISSUE THREAD

**Issue by lacastorine** [jeeliz/jeelizWeboji#60]
Accordingly to [documentation](https://github.com/jeeliz/jeelizWeboji/blob/master/doc/jeefacetransferAPI.pdf) there should be `set_animateDelay` method, but in latest build it is missing:
> JEEFACETRANSFERAPI.set_animationDelay is not a function

**Comment by xavierjs** [comment]
Because it is not `set_animationDelay` but `set_animateDelay`

**Comment by lacastorine** [comment]
Hi, sorry for typo it should be `set_animateDelay`, but it is also missing...
