### ISSUE TITLE
problem using JEELIZFACEEXPRESSIONS

### ISSUE THREAD

**Issue by HarshaSatyavardhan** [jeeliz/jeelizWeboji#62]
1. Is `JEELIZFACEEXPRESSIONS` is an updated version for  `JEEFACETRANSFERAPI` ?.
2. I was trying to use  `JEELIZFACEEXPRESSIONS` by replacing `JEEFACETRANSFERAPI` and `jeelizFaceExpressionsNNC.json` in don't drive drowsy demo but i am getting error.
3. Github link - [Link](https://github.com/HarshaSatyavardhan/drive-drowy-update/tree/main/dont-drive-drowsy-master/src)
<img width="502" alt="Screenshot 2021-05-25 120048" src="https://user-images.githubusercontent.com/41695878/119452042-89fe1f00-bd53-11eb-95f1-bffff7858f10.png">

**Comment by xavierjs** [comment]
Hi,

1. yes it has been renamed
2. The web console error is clear. 404 means that the JSON neural network model is not found. is has been renamed too

**Comment by HarshaSatyavardhan** [comment]
Thanks, 

but I have already changed the JSON neural network model also, you can check the github repo here [Link](https://github.com/HarshaSatyavardhan/drive-drowy-update/tree/main/dont-drive-drowsy-master/src). I am only facing error when i updated with `JEELIZFACEEXPRESSIONS.js` and `jeelizFaceExpressionsNNC.json`. The demo is working perfectly fine when i use `JEEFACETRANSFERAPI` and `jeelizFaceTransfer.js`.
