### ISSUE TITLE
buildJson undefined objURL

### ISSUE THREAD

**Issue by v-stickykeys** [jeeliz/jeelizWeboji#63]
`objURL` is not defined when running `buildJson.py`

Download the headmorphs and put them in the `meshConverter/meshes/` directory.
[headmorphs.zip](https://github.com/jeeliz/jeelizWeboji/files/6543237/headmorphs.zip)

Run the binary
```
./buildJson.py headmorphs
```

```
Traceback (most recent call last):
  File "./buildJson.py", line 115, in <module>
    print('WARNING for morph %s: it has %d vertices but the base mesh has %d vertices' %(objURL, len(dVertices), len(base['vertices'])))
NameError: name 'objURL' is not defined
```

Using MacOS

**Comment by v-stickykeys** [comment]
By the way, I didn't understand what the code is doing here

https://github.com/jeeliz/jeelizWeboji/blob/master/meshConverter/buildJson.py#L112-L114

It seems like the reason I run into this `not defined` error is because the vertices in my morph and the base morph are a different number. Is the expectation that they are always the same? Does it make a difference?

**Comment by xavierjs** [comment]
Read this doc about the mesh converter: https://github.com/jeeliz/jeelizWeboji/tree/master/meshConverter
And put your morphs in the right directory.
