### ISSUE TITLE
Safari Bug, not working at all

### ISSUE THREAD

**Issue by Romain-BASE-GVA** [jeeliz/jeelizWeboji#67]
I'm using Weboji through the handsfree library, and it doesn't work on Safari.

![ezgif-2-ae1f1803a2](https://user-images.githubusercontent.com/84498813/155503231-6afde993-912f-4581-8683-387eec9b1954.gif)

Safari on the left, Chrome on the right.

I'm stictly unable to get feedback on the Handsfree github, hope I'm gonna have some guidance here. Thank you.

**Comment by xavierjs** [comment]
It seems the same issue as this one: https://github.com/jeeliz/jeelizFaceFilter/issues/253
